name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install -y nasm ninja-build
    - name: Build ilo
      run: |
        ./configure
        ninja
    - name: Functional tests
      run: |
        ./test.sh
