name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up nasm
      run: |
        sudo apt install -y nasm
    - name: Build ilo
      run: |
        make ilo
    - name: Functional tests
      run: |
        make test
